spring:
  application:
    name: url-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url_db}
    username: ${SPRING_DATASOURCE_USERNAME:usher}
    password: ${SPRING_DATASOURCE_PASSWORD:usher}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
